version: '3.8'

services:
  jobapp_nc:
    container_name: jobapp_app
    image: jobapp-nc:1.0
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - jobapp_db
  jobapp_db:
    container_name: jobapp_nc_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=luis
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DD=jobapp_nc_db
    volumes:
      - nps_data:/var/lib/postgresql/

volumes:
  nps_data: {}